"""add facilitator and beneficiary tables

Revision ID: 87478ed44366
Revises: 2be52b9eb876
Create Date: 2026-03-07 21:03:05.896958

"""

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes

from app.core.encryption import EncryptedString


# revision identifiers, used by Alembic.
revision = "87478ed44366"
down_revision = "2be52b9eb876"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "facilitator",
        sa.Column("phone", sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
        sa.Column("zone", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
        sa.Column(
            "organization", sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id"),
    )
    op.create_table(
        "beneficiary",
        sa.Column("date_of_birth", sa.Date(), nullable=True),
        sa.Column("curp", EncryptedString(length=512), nullable=False),
        sa.Column("full_name", EncryptedString(length=512), nullable=False),
        sa.Column("phone", sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
        sa.Column("address", EncryptedString(length=1024), nullable=True),
        sa.Column(
            "community", sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "gender", sa.Enum("male", "female", "other", name="gender"), nullable=True
        ),
        sa.Column("facilitator_id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["facilitator_id"], ["facilitator.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_beneficiary_facilitator_id"),
        "beneficiary",
        ["facilitator_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_beneficiary_facilitator_id"), table_name="beneficiary")
    op.drop_table("beneficiary")
    op.drop_table("facilitator")
    sa.Enum("male", "female", "other", name="gender").drop(op.get_bind())
    # ### end Alembic commands ###
