"""add performance indexes on created_at status is_read resource_type

Revision ID: b8ea577dc3c0
Revises: e5fbd32d3481
Create Date: 2026-03-07 21:49:13.152128

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'b8ea577dc3c0'
down_revision = 'e5fbd32d3481'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_application_created_at'), 'application', ['created_at'], unique=False)
    op.create_index(op.f('ix_application_status'), 'application', ['status'], unique=False)
    op.create_index(op.f('ix_audit_log_created_at'), 'audit_log', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_log_resource_type'), 'audit_log', ['resource_type'], unique=False)
    op.create_index(op.f('ix_beneficiary_created_at'), 'beneficiary', ['created_at'], unique=False)
    op.create_index(op.f('ix_notification_created_at'), 'notification', ['created_at'], unique=False)
    op.create_index(op.f('ix_notification_is_read'), 'notification', ['is_read'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notification_is_read'), table_name='notification')
    op.drop_index(op.f('ix_notification_created_at'), table_name='notification')
    op.drop_index(op.f('ix_beneficiary_created_at'), table_name='beneficiary')
    op.drop_index(op.f('ix_audit_log_resource_type'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_created_at'), table_name='audit_log')
    op.drop_index(op.f('ix_application_status'), table_name='application')
    op.drop_index(op.f('ix_application_created_at'), table_name='application')
    # ### end Alembic commands ###
